[package]
name = "Redstone-daemon"
version = "0.1.0"
authors = ["LeoCornelius <leocornelius019@gmail.com>, Redstone Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = { version = "0.6", features = ["colored"] }
log = "0.4.14"
chrono = "0.4.19"
redstone_rs = { path = "../../lib"} 
secrecy = "0.7.0"
encryptfile = "0.1.3"
rocket = { version = "0.4.10", default-features = true }
lazy_static = "1.4.0"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
openssl = { version = "0.10", features = ["vendored"] }
clap = "2.33.0"
rand = "0.7.3"
tokio = { version = "1.16.1", features = ["full"] }
devise_core = "0.3.0"
pear_codegen = "0.2.3"
rocket_contrib= {version ="0.4.10", default-features=false, features=["json"]}
